apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: game-platform
  labels:
    app.kubernetes.io/name: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.game-platform.svc.cluster.local:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          httpMethod: POST

      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: http://alertmanager.game-platform.svc.cluster.local:9093
        editable: false
        jsonData:
          implementation: prometheus