apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - prometheus.yml
  - alert-rules.yml

commonLabels:
  app.kubernetes.io/part-of: game-platform
  app.kubernetes.io/managed-by: kustomize