apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: game-platform
  labels:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cassandra
  ports:
    - name: cql
      port: 9042
      targetPort: cql
    - name: jmx
      port: 7199
      targetPort: jmx
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-headless
  namespace: game-platform
  labels:
    app.kubernetes.io/name: cassandra
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: cassandra
  ports:
    - name: intra-node
      port: 7000
      targetPort: intra-node
    - name: tls-intra-node
      port: 7001
      targetPort: tls-intra-node
    - name: jmx
      port: 7199
      targetPort: jmx
    - name: cql
      port: 9042
      targetPort: cql