apiVersion: v1
kind: Namespace
metadata:
  name: game-platform
  labels:
    environment: production
    app.kubernetes.io/part-of: game-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
